
name: Deploy

on:
  push:

jobs:
    first_job:
        runs-on: ubuntu-latest

        services:
            redis:
                image: redis
                ports:
                  - 6379:6379
        
        steps:
          - name: Install redis cli
            run: sudo apt-get update -y && sudo apt-get install redis-tools -y
        
         steps:
          - name: Test redis
            run: redis-cli -h localhost -p 6379 ping

        steps:
          - name: Print variable
            run: echo "${{ secrets.YOUR_DEFINED_SECRET }}"

          - name: setup
            uses: actions/setup-node@v4
            with:
                node-version: '18'



