
name: Deploy

on:
  push:

jobs:
  first_job:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install redis cli
        run: sudo apt-get update -y && sudo apt-get install redis-tools -y

      - name: Test redis
        run: redis-cli -h localhost -p 6379 ping


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install
        working-directory: .

      - name: Run test
        run: npm run test
        working-directory: .

      - name: build page
        run: npm run build
        working-directory: .

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
         path: public/
    
 
  deploy:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: first_job

    permissions:
        pages: write
        id-token: write
    
    environment:
        name: github-page
        url: ${{ steps.deployment-pages.outputs.page_url }}



    steps:
      - name: Deploy
        id: deployment-pages
        uses: actions/deploy-pages@v4


